#!/sbin/openrc-run

supervisor=supervise-daemon
respawn_delay=10

name="Hetzner Dynamic DNS Daemon"
description="Continuously update your servers' A and AAAA records with dynamic IP addresses."

command="/usr/local/bin/${RC_SVCNAME} -V -c /usr/local/etc/hetzner_ddns.json"
command_user=daemon:daemon

depend() {
	need net
	use dns netmount
	after bootmisc
}

start_pre() {
	chown daemon:daemon /usr/local/etc/hetzner_ddns.json
}
