#!/sbin/openrc-run

supervisor=supervise-daemon
respawn_delay=10

name="Hetzner Dynamic DNS Daemon"
description="A simple daemon to continuously update Hetzner DNS A and AAAA records for your server with a dynamic IP address"

command="/usr/local/bin/${RC_SVCNAME}"
command_user=daemon:daemon

depend() {
	need net
	use dns netmount
	after bootmisc
}

start_pre() {
	touch /var/log/hetzner_ddns.log
	chown daemon:daemon /var/log/hetzner_ddns.log /usr/local/etc/hetzner_ddns.conf
}
