.TH hetzner_ddns 1 "2025-11-07" "hetzner_ddns 1.0.1" "Manual for hetzner_ddns"
.SH NAME
hetzner_ddns \- Hetzner Dynamic DNS Daemon
.SH SYNOPSIS
.B hetzner_ddns
[\fB\-c\fR \fIconfig_file\fR]
[\fB\-l\fR \fIlog_file\fR]
[\fB\-V\fR]
[\fB\-d\fR]
[\fB\-h\fR]
[\fB\-v\fR]
.SH DESCRIPTION
.B hetzner_ddns
Continuously update your servers' A and AAAA records with dynamic IP addresses.
.SH OPTIONS
.TP
.BR \-c " " \fIconfig_file\fR
Use specified configuration file
.TP
.BR \-l " " \fIlog_file\fR
Use specified log file
.TP
.BR \-P " " \fIpid_file\fR
Use specified PID file when daemonized
.TP
.BR \-V
Display all log messages to stderr
.TP
.BR \-d
Detach from current shell and run as a daemon
.TP
.BR \-h
Print help and exit
.TP
.BR \-v
Print version and exit
.SH CONFIGURATION
The configuration file uses JSON format with the following structure:
.SS settings
.TP
.BR log_file
Path to a custom configuration file
.TP
.BR ip_check_cooldown
Time between subsequent checks of interface's IP address
.TP
.BR request_timeout
Maximum duration of HTTP requests
.TP
.BR api_url
URL of the Hetzner Console's API
.TP
.BR ip_url
URL of a service for retrieving external IP addresses
.SS defaults
.TP
.BR type
Default record type (can be "A", "AAAA", or "A/AAAA")
.TP
.BR interface
Default network interface name (auto-detect if unspecified)
.TP
.BR ttl
Default TTL value in seconds (60 <= TTL <= 2147483647)
.SS zones
An array of zone objects, each containing:
.TP
.BR domain
Domain name of a zone
.TP
.BR records
An array of record objects, each containing:
.RS
.TP
.BR name
Name of the record (use @ for domain's root)
.TP
.BR type
Override of the default record type
.TP
.BR ttl
Override of the default TTL
.TP
.BR interface
Override of the default interface
.RE
.SH USAGE
.TP
.B Run on startup
service hetzner_ddns enable
.TP
.B Start
service hetzner_ddns start
.TP
.B Stop
service hetzner_ddns stop
.TP
.B Trigger update of all records
service hetzner_ddns reload
